=== rbowensv/tts/mod/schema/Unit.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://schema.swlegion.dev/deps/Unit.json",

  "title": "Unit Card",
  "description": "Definition of a unit card.",

  "definitions": {
    "Bases": {
      "enum": [
        "small",
        "medium",
        "large",
        "huge",
        "laat",
        "epic",
        "long",
        "snail"
      ]
    }
  },

  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },

    "title": {
      "type": "string",
      "minLength": 1
    },

    "displayName": {
      "description": "Optional. If provided, is used instead of name or title for list building purposes.",
      "type": "string",
      "minLength": 1
    },

    "image": {
      "$ref": "./Image.json"
    },

    "size": {
      "description": "Size of the base.",
      "$ref": "#/definitions/Bases"
    },

    "type": {
      "anyOf": [
        { "$ref": "./UnitTypes.json" },
        {
          "type": "string",
          "minLength": 1
        }
      ]
    },

    "hover": {
      "description": "Optional. The unit's Hover keyword: \"ground\" means it blocks line of sight and provides cover like a ground vehicle.",
      "enum": ["ground", "air"]
    },

    "silhouette": {
      "type": "object",
      "description": "Optional.  Height and Offset values for a Custom Silhouette.",
      "properties": {
        "height": { "type" : "number" },
        "offset": { "type" : "number" }
      }
    },

    "heavyWeaponTeam": {
      "description": "Reqyure a \"Heavy Weapon\" upgrade attached to this unit and make it the unit leader.",
      "enum": [true]
    },

    "minis": {
      "oneOf": [
        {
          "description": "Number of placeholder minis to spawn",
          "type": "number",
          "minimum": 1
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "./Mini.json"
          }
        }
      ]
    },

    "points": {
      "type": "number",
      "minimum": 0
    },

    "speed": {
      "type": "number",
      "minimum": 0
    },

    "height": {
      "description": "The approximate height of the model, in inches. The default, which is intended for small-base (trooper) minis, is 2.",
      "type": "number",
      "minimum": 1,
      "default": 2,
      "maximum": 10
    },

    "upgrades": {
      "additionalProperties": {
        "type": "number",
        "minimum": 1
      },

      "propertyNames": {
        "anyOf": [
          { "$ref": "./Upgrades.json" },
          {
            "type": "string",
            "minLength": 1
          }
        ]
      },

      "type": "object"
    },

    "commands": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "./CommandCard.json"
      }
    },

    "required": {
      "type": "array",
      "description": "Required upgrades or flaw cards, by name.",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    },

    "additionalObjects": {
      "$ref": "./AdditionalObjects.json"
    }
  },

  "additionalProperties": false,
  "type": "object",
  "required": ["name", "image", "size", "type", "points", "speed", "upgrades"]
}

=== rbowensv/tts/contrib/cards/Mercenary/WLO5SpeederTankUnit.json
{
  "name": "WLO-5 Speeder Tank",
  "image": "https://steamusercontent-a.akamaihd.net/ugc/12892745162360850606/8F7C7F70F1604DCA9BB39BE0F0EE859149D3A3F8/",
  "size": "snail",
  "type": "Repulsor Vehicle",
  "hover": "ground",
  "points": 100,
  "speed": 1,
  "upgrades": {
    "Crew": 1,
    "Pilot": 1,
    "Comms": 1
  },
  "silhouette": {
    "height": 2.44,
    "offset": 0
  },
  "minis": [
    {
      "mesh": "https://steamusercontent-a.akamaihd.net/ugc/18162736975687770648/643CAEA98913694A90A7BC6B9ED78668C9F46386/",
      "diffuse": "https://steamusercontent-a.akamaihd.net/ugc/14670109106110705253/18525D8840EEFDB2DC159B4988BD6A734BC2418E/",
      "collider": "https://steamusercontent-a.akamaihd.net/ugc/10402477424751392481/9585E316040CEA861ABF6A551F35C2473BEC0C52/"
    }
  ]
}
